# Generated by Django 4.2.26 on 2025-11-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('dateStart', models.DateTimeField(max_length=100)),
                ('dateEnd', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dateStart', models.DateTimeField(max_length=100)),
                ('dateEnd', models.DateTimeField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skillstype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skillStartDate', models.DateTimeField(blank=True, max_length=100)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('skillid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skillStartDate', models.DateTimeField(blank=True, max_length=100)),
                ('employmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employment')),
                ('skillid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills')),
            ],
        ),
    ]
